products:
- trolmaster
- athena ag
- azramax
- bio canna
- bluelab
- bubble magic
- cultured biologix
- digilux
- fiskar
- gardening indoors
- gavita
- greengro
- growers choice
- heavy 16
- hortilux
- karma works
- kind
- magicalbutter
- mammoth
- mars
- neptunes harvest 
- purple cow
- roots organics
